# Generated by Django 4.2.16 on 2024-11-19 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_mvola', '0002_mvolaorderpayment_server_corelation_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mvolaorderpayment',
            old_name='server_corelation_id',
            new_name='server_correlation_id',
        ),
    ]
